/* A program to find triangle numbers with a given number of divisors.
 *
 * Two functions make up this program. number_of_divisors(x) works for
 * any non-negative long x. Returns how many factors that number has in
 * O(sqrt(x) time).
 *
 * triangle_number_divisibility(divisors) calculates the triangle
 * numbers and checks each using number_of_divisors(). Runs until
 * number_of_divisors(triangle_number) > divisors. 
 *
 * Runtime: quadratic but uses sqrt, so O(n * sqrt(n)) */

# include <stdio.h>
# include <stdlib.h>
# include "../minunit.h"

# include <math.h>

/* Testing function prototype */
static char * all_tests();

/* Test counter. Incremented by minunit.h */
int tests_run = 0;

int main() {
    /* 
     * The reults of all_tests() from minunit.h will == 0 when all 
     * tests pass. Otherwise, all_tests() will return a string 
     * describing the failure. 
    */
    char *result = all_tests();
    if (result != 0) {
        printf("%s\n", result);
    }
    else {
        printf("ALL TESTS PASSED\n");
    }
    
    /* 
     * minunit.h counts the number of tests it ran, in order listed in
     * all_tests() below, until a test fails and all_tests quits. 
    */
    printf("Tests run %d\n", tests_run);
    
    return result != 0;
}

/* PROGRAM */
/* Unsigned long argument - testing shows won't surpass 4 billion. */
int number_of_divisors(unsigned long x) {
    int divisors = 0;
    unsigned long root = sqrt(x);
    unsigned long i;

    /* Only need to go up to sqrt(x). Add 2 when there's a complement
     * >sqrt(x) */
    for (i = 1; i <= root; i++) {
        if (x % i == 0) {
            /* Add 1 when i is the exact sqrt(x). Aka i == x/i. Don't
             * count it twice. */
            if (i == x/i) {
                divisors++;
            }
            else {
                divisors += 2;
            }
        }
    }
    return divisors;
}

unsigned long triangle_number_divisibility(int divisors) {
    if (divisors < 1) {
        return 0;
    }
    else if (divisors >= 1) {
        /* The sequence of triangle numbers is generated by adding the
         * natural numbers. So the 7th triangle number would be 1 + 2 +
         * 3 + 4 + 5 + 6 + 7 = 28 */
        unsigned long triangle_number = 1;
        unsigned long i;

        for (i = 2; ; i++) {
            if (number_of_divisors(triangle_number) > divisors) {
                return triangle_number;
            }
            else {
                triangle_number += i;
            }
        }
    }
}


/* TESTS */
static char * test_divisors_1() {
    mu_assert("number_of_divisors(1) != 1", number_of_divisors(1) == 1);
    return 0;
}

static char * test_divisors_6() {
    mu_assert("number_of_divisors(6) != 4", number_of_divisors(6) == 4);
    return 0;
}

static char * test_trinum_1() {
    mu_assert("triangle_number_divisibility(1) != 3", \
            triangle_number_divisibility(1) == 3);
    return 0;
}

static char * test_trinum_5() {
    mu_assert("triangle_number_divisibility(5) != 28", \
            triangle_number_divisibility(5) == 28);
    return 0;
}

static char * test_trinum_500() {
    mu_assert("triangle_number_divisibility(500) != 76,576,500", \
            triangle_number_divisibility(500) == 76576500);
    return 0;
}

static char * all_tests() {
    mu_run_test(test_divisors_1);
    mu_run_test(test_divisors_6);
    mu_run_test(test_trinum_1);
    mu_run_test(test_trinum_5);
    mu_run_test(test_trinum_500);

    return 0;
}
